### ISSUE TITLE
Compiling Problems

### ISSUE THREAD

**Issue by ghost** [maxritter/diy-thermocam#7]
Hello,
I'm trying to build a version of the DIYThermoCam and I'm trying to get the DIY-Thermocam.ino to compile in the Arduino IDE version 1.8.3 with board settings set to Teensy (I've tried setting the board to both the 3.2/3.1, and the 3.6 options).  When I do, it always gives me the errors seen below: 

C:\Users\Student\AppData\Local\Temp\arduino_build_408755\sketch\Thermal/Load.h:785: undefined reference to `FatFile::openNext(FatFile*, unsigned char)'

C:\Users\Student\AppData\Local\Temp\arduino_build_408755\sketch\Thermal/Load.h:826: undefined reference to `FatFile::close()'

"C:\Users\Student\AppData\Local\Temp\arduino_build_408755\sketch\Thermal/Load.h:813: undefined reference to `FatFile::close()'".  

I went to the address shown in the above error and I couldn't find anything related to it in the Load.h file. I couldn't find anything in where the actual file was saved when I downloaded the firmware either.  I didn't change anything in the files after I downloaded them from Github.  Also, what Programmer should the IDE be set to use? It's currently set to "Atmel SAM-ICE". Could you help me fix this please?

**Comment by maxritter** [comment]
You need to use Visual Studio 2015/2017 together with VisualMicro to compile the project.

Follow the instruction guide here: https://github.com/maxritter/DIY-Thermocam/tree/master/Firmware/Source

Wishes,
Max
